USE [master]
GO

/****** Object:  Database [MMtools]    Script Date: 28/09/2016 03:26:23 p.m. ******/
CREATE DATABASE [MMtools]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MMtools', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\MMtools.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MMtools_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\MMtools_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MMtools] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MMtools].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MMtools] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MMtools] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MMtools] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MMtools] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MMtools] SET ARITHABORT OFF 
GO

ALTER DATABASE [MMtools] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MMtools] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MMtools] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MMtools] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MMtools] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MMtools] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MMtools] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MMtools] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MMtools] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MMtools] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MMtools] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MMtools] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MMtools] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MMtools] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MMtools] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MMtools] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MMtools] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MMtools] SET RECOVERY FULL 
GO

ALTER DATABASE [MMtools] SET  MULTI_USER 
GO

ALTER DATABASE [MMtools] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MMtools] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MMtools] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MMtools] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MMtools] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MMtools] SET  READ_WRITE 
GO




USE [MMtools]
GO

/****** Object:  Table [dbo].[Clientes]    Script Date: 28/09/2016 04:04:22 p.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Clientes](
	[ClienteId] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [nvarchar](500) NOT NULL,
	[Email] [nvarchar](500) NOT NULL,
	[DataCadastro] [datetime] NOT NULL,
	[DataModificacao] [datetime] NULL,
	[Telefone] [nvarchar](500) NOT NULL,
	[Ativo] [bit] NOT NULL,
	[Cpf] [nvarchar](500) NULL,
	[DataNascimento] [datetime] NULL,
 CONSTRAINT [PK_Clientes] PRIMARY KEY CLUSTERED 
(
	[ClienteId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Clientes] ADD  CONSTRAINT [DF_Clientes_DataCadastro]  DEFAULT (getdate()) FOR [DataCadastro]
GO

ALTER TABLE [dbo].[Clientes] ADD  CONSTRAINT [DF_Clientes_DataModificacao]  DEFAULT (getdate()) FOR [DataModificacao]
GO

ALTER TABLE [dbo].[Clientes] ADD  CONSTRAINT [DF_Clientes_Ativo]  DEFAULT ((1)) FOR [Ativo]
GO



